### ISSUE TITLE
Picker Android "dialog" not applicable

### ISSUE THREAD

**Issue by ChaeWonKong** [react-native-community/react-native-picker#24]
# Bug
When using picker in android, changing mode to 'dialog' is never being applied.
Always working as 'dropdown' not 'dialog',

## Environment info
picker version: 1.1.1

React native info output:

```bash
System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 242.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
```

Library version: 1.1.1

## Steps To Reproduce

1. Install Picker
2. add dialog mode
...

Describe what you expected to happen:

1. when change mode to 'dialog', I expect modal open for picker selection

## Reproducible sample code

My code:
```react
 <Picker
              selectedValue={this.state.type}
              style={{
                width: 100,
                color: "#fff"
              }}
              prompt="오전/오후"
              mode="dialog"
              itemStyle={{
                color: "white"
              }}
              // style={{ height: 50, width: 100 }}
              onValueChange={(itemValue, itemIndex) =>
                this.setState({ type: itemValue })
              }
            >
              <Picker.Item label="오후" value="night" />
              <Picker.Item label="오전" value="dawn" />
            </Picker>
```

**Comment by moinulhuq** [comment]
Yes Same here. Not showing any "**dialog**"

**Comment by chakrihacker** [comment]
Hi, I have tested the snippet you shared and it works fine in android device. Are you still facing the issue??

**Comment by chakrihacker** [comment]
Closing this issue as this is stale for more than 1 month

**Comment by fnequal** [comment]
same here. with rn 0.67.4 and picker 2.4.8
logcat error when touch selected item, not showing any dialog

`Unhandled SoftException
    com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches: ReactTag[16908308] UIManagerType[2] EventName[topTouchStart]
        at com.facebook.react.uimanager.events.ReactEventEmitter.receiveTouches(ReactEventEmitter.java:82)
        at com.facebook.react.uimanager.events.TouchesHelper.sendTouchEvent(TouchesHelper.java:101)
        at com.facebook.react.uimanager.events.TouchEvent.dispatch(TouchEvent.java:193)
        at com.facebook.react.uimanager.events.TouchEvent.dispatchModern(TouchEvent.java:201)
        at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:374)
        at android.os.Handler.handleCallback(Handler.java:955)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:206)
        at android.os.Looper.loop(Looper.java:296)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:930)`

**Comment by antoxa2584x** [comment]
Same here on latest versuion
